import Head from "next/head";

const Home = () => {
  return (
    <div className="z-0">
      <Head>
        <title>Apex Legends Lookup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/apex-logo.webp" />
      </Head>
      <section className="text-center my-auto text-black ">
        <h1 className="text-3xl mt-6 lg:text-6xl lg:mt-12 p-2 ">Welcome</h1>
        <h3 className="text-xl  lg:text-3xl lg:m-1 p-2">to the</h3>
        <img
          src="/apex-bg-removebg-preview.webp"
          className="lg:max-w-7xl my-2 md:my-0 mx-auto"
          alt={"ERR"}
        />
        <h2 className="text-2xl lg:text-5xl">Stat Lookup!</h2>
      </section>
      <section className="lg:max-w-2xl p-1 m-1 mt-2 mx-auto">
        <div className="mx-1 md:mx-2">
          <label
            htmlFor="system"
            className="block text-lg font-medium text-black"
          >
            System
          </label>
          <select
            id="system"
            name="system"
            className="mt-1 block pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md"
            defaultValue="Playstation"
          >
            <option>Playstation</option>
            <option>Xbox</option>
            <option>PC</option>
          </select>
        </div>
        <div className="mx-1 md:mx-2">
          <label
            htmlFor="gamertag"
            className="block text-sm font-medium text-gray-700"
          >
            Gamertag
          </label>
          <input
            className="flex w-full  focus:ring-indigo-500 focus:border-indigo-500 rounded sm:text-sm border-gray-300"
            type={"text"}
            name="gamertag"
            id="gamertag"
          />
        </div>
        <div className="mx-1 md:mx-2">
          <button
            type={"button"}
            className="w-full  mt-4  py-1.5 lg:px-4 lg:py-2 rounded-xl bg-muted-dark-red text-white text-lg"
          >
            Search
          </button>
        </div>
      </section>
    </div>
  );
};

export default Home;
