import Head from "next/head";

const Home = () => {
  return (
    <div className="z-0">
      <Head>
        <title>Apex Legends Lookup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/apex-logo.webp" />
      </Head>
      <div>Hello</div>
    </div>
  );
};

export default Home;
